#ifndef DEF_SIEGE_OF_NIUZAO_TEMPLE_H_
#define DEF_SIEGE_OF_NIUZAO_TEMPLE_H_

#define MAX_ENCOUNTERS 4

enum Creatures
{
	BOSS_COMMANDER_VOJAK   = 61634,
    BOSS_GENERAL_PAVALAK  = 61485,
    BOSS_VIZIER_JINBAK  = 61567,
	BOSS_WING_LEADER_NERONOK = 62205,   
};

enum Objects
{
    
};

enum Data
{
	DATA_VIZIER_JINBAK  = 1,
    DATA_COMMANDER_VOJAK   = 2,
    DATA_GENERAL_PAVALAK  = 3,    
	DATA_WING_LEADER_NERONOK = 4,
};

#endif
