#ifndef DEF_GATE_OF_THE_SETTING_SUN_H_
#define DEF_GATE_OF_THE_SETTING_SUN_H_

#define MAX_ENCOUNTERS 4

enum Creatures
{
	BOSS_COMMANDER_RIMOK   = 56636,
    BOSS_RAIGONN   = 56877,
    BOSS_SABOTEUR   = 56906,
	BOSS_STRIKER_GADOK = 56589,    
};

enum Objects
{
    
};

enum Data
{
    DATA_SABOTEUR   = 1,
	DATA_STRIKER_GADOK = 2,
	DATA_COMMANDER_RIMOK   = 3,
	DATA_RAIGONN   = 4,
};

#endif
