
MACRO( GenerateProject ProjectDirectory ProjectSources )
	SET( DirectorySources "${ProjectSources}" )
	FOREACH( Source ${DirectorySources} )
		if ("${Source}" MATCHES "(/)+")
			STRING( REGEX REPLACE "${ProjectDirectory}" "" RelativePath "${Source}" )
			STRING( REGEX REPLACE "[\\\\/][^\\\\/]*$" "" RelativePath "${RelativePath}" )
			STRING( REGEX REPLACE "^[\\\\/]" "" RelativePath "${RelativePath}" )
			STRING( REGEX REPLACE "/" "\\\\\\\\" RelativePath "${RelativePath}" )
			SOURCE_GROUP( "${RelativePath}" FILES ${Source} )
		else()
			SOURCE_GROUP( "" FILES ${Source} )
		endif()
	ENDFOREACH( Source )
ENDMACRO( GenerateProject )
