/* Script de Tydrheal & Sungis : Temple du serpent de jade. */

#ifndef DEF_TEMPLE_OF_THE_JADE_SERPENT_H
#define DEF_TEMPLE_OF_THE_JADE_SERPENT_H

enum Data64
{
	DATA_BOSS_WISE_MARI,
	DATA_WISE_MARI_GATE,
	DATA_BOSS_LOREWALKER_STONESTEP,
	DATA_NPC_ZAO_SUNSEEKER,
	DATA_BOSS_LIU_FLAMEHEART,
	DATA_BOSS_SHA_OF_DOUBT
};

enum CreatureIds
{
	BOSS_WISE_MARI				= 56448,
	BOSS_LOREWALKER_STONESTEP	= 56843,
	NPC_ZAO_SUNSEEKER			= 58826,
	BOSS_LIU_FLAMEHEART			= 56732,
	BOSS_SHA_OF_DOUBT			= 56439
};

enum GameObjects
{
	GO_SHA_OF_DOUBT_GATE	= 400426,
	GO_LIU_GATE				= 400427,
	GO_MARI_LOREWALKER_GATE	= 400428,
};

#endif

