/* Script de Tydrheal : Monastère des Pandashan. */

#ifndef DEF_SHADOPAN_MONASTERY_H
#define DEF_SHADOPAN_MONASTERY_H

enum Data64
{
	DATA_BOSS_GU_CLOUDSTRIKE,
	DATA_NPC_AZURE_SERPENT,
	DATA_BOSS_MASTER_SNOWDRIFT,
	DATA_BOSS_SHA_OF_VIOLENCE,
	DATA_BOSS_TARAN_ZHU,
};

enum CreaturesIds
{
	BOSS_GU_CLOUDSTRIKE		= 56747,
	NPC_AZURE_SERPENT		= 56754,
	BOSS_MASTER_SNOWDRIFT	= 56541,
	BOSS_SHA_OF_VIOLENCE	= 56719,
	BOSS_TARAN_ZHU			= 56884,

};


#endif
