#ifndef DEF_HEART_OF_FEAR_H_
#define DEF_HEART_OF_FEAR_H_

#define MAX_ENCOUNTERS 6

enum Creatures
{
	BOSS_AMBERSHAPER_UNSOK   = 62511,
    BOSS_BLADE_LORD_TAYAK   = 62543,
    BOSS_GARALON   = 62164,
	BOSS_GRAND_EMPRESS_SHEKZEER = 62837,
	BOSS_IMPERIAL_VIZIER_ZORLOK = 62980,
	BOSS_WIND_LORD_MELJARAK = 62397,   
};

enum Objects
{
    
};

enum Data
{
    DATA_IMPERIAL_VIZIER_ZORLOK = 1,
    DATA_BLADE_LORD_TAYAK   = 2,
    DATA_GARALON   = 3,
	DATA_WIND_LORD_MELJARAK = 4,
	DATA_AMBERSHAPER_UNSOK   = 5,
	DATA_GRAND_EMPRESS_SHEKZEER = 6,		
};

#endif
