#ifndef DEF_SCHOLOMANCE_H_
#define DEF_SCHOLOMANCE_H_

#define MAX_ENCOUNTERS 5

enum Creatures
{
	BOSS_DARKMASTER_GANDLING   = 59080,
    BOSS_INSTRUCTOR_CHILLHEART   = 58633,
    BOSS_JANDICE_BAROV   = 59184,
	BOSS_LILIAN_VOSS = 58722,
	BOSS_RATTLEGORE = 59153,   
};

enum Objects
{
    
};

enum Data
{    
    DATA_INSTRUCTOR_CHILLHEART   = 1,
    DATA_JANDICE_BAROV   = 2,
	DATA_RATTLEGORE = 3,
	DATA_LILIAN_VOSS = 4,	
	DATA_DARKMASTER_GANDLING   = 5,
};

#endif
