/* Script de Sungis : Palais Mogu'shan. */

#ifndef DEF_MOGUSHAN_PALACE_H
#define DEF_MOGUSHAN_PALACE_H

enum Data64
{
	DATA_NPC_XIN_THE_WEAPONMASTER,
	DATA_KUAI_THE_BRUTE,
	DATA_MUSHIBA,
	DATA_MING_THE_CUNNING,
	DATA_HAIYAN_THE_UNSTOPPABLE,
	DATA_GEKKAN,
	DATA_ANCIENT_MOGU_TREASURE,
	DATA_GLINTROK_ORACLE,
	DATA_GLINTROK_HEXXER,
	DATA_MOB_GLINTROK_HEXXER,
	DATA_GLINTROK_SKULKER,
	DATA_GLINTROK_IRONHIDE,
	DATA_BOSS_XIN_THE_WEAPONMASTER,
};

enum CreaturesIds
{
	NPC_XIN_THE_WEAPONMASTER	= 61884,
	BOSS_KUAI_THE_BRUTE			= 61442,
	BOSS_MUSHIBA				= 61453,
	BOSS_MING_THE_CUNNING		= 61444,
	BOSS_HAIYAN_THE_UNSTOPPABLE	= 61445,
	BOSS_GEKKAN					= 61243,
	NPC_GLINTROK_ORACLE			= 61339,
	NPC_GLINTROK_HEXXER			= 61340,
	NPC_GLINTROK_SKULKER		= 61338,
	NPC_GLINTROK_IRONHIDE		= 61337,
	BOSS_XIN_THE_WEAPONMASTER	= 61398
};

enum GameObjectIds
{
	GO_ANCIENT_MOGU_TREASURE	= 214794,
};

#endif
