#ifndef DEF_TERRACE_OF_THE_ENDLESS_SPRING_H_
#define DEF_TERRACE_OF_THE_ENDLESS_SPRING_H_

#define MAX_ENCOUNTERS 4

enum Creatures
{
	BOSS_LEI_SHI   = 62983,
    BOSS_PROTECTORS_OF_THE_ENDLESS  = 60583,
    BOSS_SHA_OF_FEAR  = 60999,
	BOSS_TSULONG = 62442,   
};

enum Objects
{
    
};

enum Data
{  
    DATA_PROTECTORS_OF_THE_ENDLESS  = 1,
    DATA_TSULONG = 2,
	DATA_LEI_SHI   = 3,
	DATA_SHA_OF_FEAR  = 4,
};

#endif
